CREATE TABLE `petting`.`MEMBERS` (
  `MEMBER_ID` INT NOT NULL AUTO_INCREMENT COMMENT '會員ID流水號',
  `NAME` VARCHAR(25) NOT NULL COMMENT '姓名',
  `MOBILE` VARCHAR(25) NOT NULL COMMENT '手機',
  `PHONE` VARCHAR(10) NULL COMMENT '電話',
  `ADDRESS` VARCHAR(50) NOT NULL COMMENT '住址',
  `DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '註冊日期',
  `EMAIL` VARCHAR(50) NOT NULL COMMENT '信箱',
  `PASSWORD` VARCHAR(25) NOT NULL COMMENT '密碼',
  `NICKNAME` VARCHAR(25) NULL COMMENT '暱稱',
  `INTRO` VARCHAR(250) NULL COMMENT '簡介',
  `PHOTO` BLOB NULL COMMENT '大頭貼',
  PRIMARY KEY (`MEMBER_ID`),
  UNIQUE (`EMAIL`)
) COMMENT = '會員資料表';

CREATE TABLE `petting`.`BUS` (
  `BUS_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商家ID',
  `NAME` VARCHAR(25) NOT NULL COMMENT '商家名稱',
  `PHONE` VARCHAR(25) NOT NULL COMMENT '電話',
  `ADDRESS` VARCHAR(50) NOT NULL COMMENT '地址',
  `TAX_ID` VARCHAR(8) NULL COMMENT '統編',
  `DATE` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '註冊日期',
  `EMAIL` VARCHAR(25) NOT NULL COMMENT '帳號',
  `PASSWORD` VARCHAR(25) NOT NULL COMMENT '密碼',
  `INTRO` VARCHAR(250) NULL COMMENT '簡介',
  `PHOTO` BLOB NULL COMMENT '大頭貼',
  `FB` VARCHAR(30) NULL COMMENT 'FB',
  `IG` VARCHAR(30) NULL COMMENT 'IG',
  `WEBSITE` VARCHAR(30) NULL COMMENT '官方網站',
  `PAYMENT_PROVIDE` VARCHAR(4) NULL COMMENT '提供的付款方式',
  PRIMARY KEY (`BUS_ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE,
  UNIQUE INDEX `TAX_ID_UNIQUE` (`TAX_ID` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE
)COMMENT = '商家會員資料表';
  
CREATE TABLE `petting`.`MEM_FOLLOW` (
  `FRIENDSHIP_ID` INT NOT NULL AUTO_INCREMENT COMMENT '追蹤ID流水編號',
  `MEMBER_ID` INT NOT NULL COMMENT '會員ID',
  `FOLLOWEE` INT NOT NULL COMMENT '對象會員ID',
  `FRIENDSHIP` VARCHAR(1) default 0 COMMENT '關係,',
  PRIMARY KEY (`FRIENDSHIP_ID`),
  INDEX `FK_FOLLOW_MEMBER_ID_idx` (`MEMBER_ID` ASC) VISIBLE,
  INDEX `FK_FOLLOW_FOLLOWEE_idx` (`FOLLOWEE` ASC) VISIBLE,
  CONSTRAINT `FK_FOLLOW_MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `pet_g3db_tfa105_beta2`.`MEMBERS` (`MEMBER_ID`),
  CONSTRAINT `FK_FOLLOW_FOLLOWEE`
    FOREIGN KEY (`FOLLOWEE`)
    REFERENCES `pet_g3db_tfa105_beta2`.`MEMBERS` (`MEMBER_ID`)
)COMMENT = '追蹤_黑名單的個人';

CREATE TABLE `petting`.`MEM_TRACK_BUS` (
  `BUSFOLLOW_ID` INT NOT NULL AUTO_INCREMENT COMMENT'流水編號',
  `MEMBER_ID` INT NOT NULL COMMENT '會員ID',
  `BUS_ID` INT NULL COMMENT '商家ID',
  PRIMARY KEY (`BUSFOLLOW_ID`),
  INDEX `MEMBER_ID_idx` (`MEMBER_ID` ASC) VISIBLE,
  INDEX `BUS_ID_idx` (`BUS_ID` ASC) VISIBLE,
  CONSTRAINT `MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `pet_g3db_tfa105_beta2`.`MEMBERS` (`MEMBER_ID`),
  CONSTRAINT `BUS_ID`
    FOREIGN KEY (`BUS_ID`)
    REFERENCES `pet_g3db_tfa105_beta2`.`BUS` (`BUS_ID`)
)COMMENT = '追蹤的商家';

CREATE TABLE `petting`.`MEM_BLOG_ART` (
    `ART_ID` INTEGER COMMENT '文章ID(流水號)' AUTO_INCREMENT PRIMARY KEY,
    `BLOG_MEMBER_ID` INTEGER COMMENT '會員ID' NOT NULL,
    `TITLE` VARCHAR(100) COMMENT '標題' NOT NULL,
    `POSTTIME` TIMESTAMP COMMENT '發文時間' DEFAULT NOW(),
    `HEART` INTEGER COMMENT '愛心數' NOT NULL,
    `CONTENT` VARCHAR(1000) COMMENT '內文' NOT NULL,
    FOREIGN KEY(`BLOG_MEMBER_ID`) REFERENCES `MEMBERS`(`MEMBER_ID`)
)COMMENT = '論壇文章';

CREATE TABLE `petting`.`MEM_HEART` (
    `HE_ART_ID` INTEGER COMMENT '文章ID(流水號)' AUTO_INCREMENT,
    `HE_MEMBER_ID` INTEGER COMMENT '會員ID' NOT NULL,
    TIME TIMESTAMP COMMENT '時間' DEFAULT NOW(),
    FOREIGN KEY(`HE_ART_ID`) REFERENCES `MEM_BLOG_ART`(`ART_ID`),
    FOREIGN KEY(`HE_MEMBER_ID`) REFERENCES `MEMBERS`(`MEMBER_ID`),
    PRIMARY KEY(`HE_ART_ID`, `HE_MEMBER_ID`)
)COMMENT = '愛心數紀錄';

CREATE TABLE `petting`.`MEM_SAVED_ART` (
    `SAV_ID` INTEGER COMMENT '流水編號' AUTO_INCREMENT PRIMARY KEY,
    `SAV_MEMBER_ID` INTEGER COMMENT '會員ID' NOT NULL,
    `SAV_ART_ID` INTEGER COMMENT '文章ID(流水號)' NOT NULL,
    TIME TIMESTAMP COMMENT '時間' DEFAULT NOW(),
    FOREIGN KEY(`SAV_ART_ID`) REFERENCES `MEM_BLOG_ART`(`ART_ID`),
    FOREIGN KEY(`SAV_MEMBER_ID`) REFERENCES `MEMBERS`(`MEMBER_ID`)
)COMMENT = '用戶收藏的文章';

CREATE TABLE `petting`.`MEM_REPLY` (
    `RE_ID` INTEGER COMMENT '回應流水ID' AUTO_INCREMENT PRIMARY KEY,
    `RE_ART_ID` INTEGER COMMENT '文章ID(流水號)' NOT NULL,
    `RE_MEMBER_ID` INTEGER COMMENT '會員ID' NOT NULL,
    `RE` VARCHAR(255) COMMENT '留言回應內容' NOT NULL,
    TIME TIMESTAMP COMMENT '時間' DEFAULT NOW(),
    FOREIGN KEY(`RE_ART_ID`) REFERENCES `MEM_BLOG_ART`(`ART_ID`),
    FOREIGN KEY(`RE_MEMBER_ID`) REFERENCES `MEMBERS`(`MEMBER_ID`)
)COMMENT = '留言回應';

CREATE TABLE `petting`.`MEM_ART_PIC` (
    `BL_ARTPIC_ID` INTEGER COMMENT '文圖關聯ID(流水號)' AUTO_INCREMENT PRIMARY KEY,
    `BL_ART_ID` INTEGER COMMENT '文章ID' NOT NULL,
    `BL_ART_PIC` BLOB COMMENT '圖片',
    `TIME` DATE COMMENT '時間' NULL, -- DEFAULT NOW()
    FOREIGN KEY(`BL_ART_ID`) REFERENCES `MEM_BLOG_ART`(`ART_ID`)
)COMMENT = '文章的圖片';

CREATE TABLE `petting`.`MER` (
  `MER_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品ID流水編號',
  `BUS_ID` INT NOT NULL COMMENT '商家ID',
  `NAME` VARCHAR(25) NOT NULL COMMENT '商品名稱',
  `PRICE` INT NOT NULL COMMENT '商品價格',
  `STOCK` INT NOT NULL COMMENT '庫存量',
  `SHELF_DATE` DATE NULL COMMENT '上架日期',
  `STATUS` INT NULL COMMENT '上架狀態',
  `DESCRIPTION` VARCHAR(250) NULL COMMENT '商品描述',
  `SHIPPING_METHOD` VARCHAR(3) NULL COMMENT '提供的出貨方式',
  `MAIN_CATEGORY` VARCHAR(50) NULL COMMENT '主商品類別',
  `SUB_CATEGORY` VARCHAR(50) NULL COMMENT '子商品類別',
  PRIMARY KEY (`MER_ID`),
  FOREIGN KEY (`BUS_ID`) REFERENCES `BUS`(`BUS_ID`)
) COMMENT '商品資料表';

CREATE TABLE `petting`. `MER_IMG` (
  `IMG_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品圖流水編號',
  `MER_ID` INT NOT NULL COMMENT '商品ID',
  `MER_PIC` BLOB NOT NULL COMMENT '圖片',
  `TIME` DATE NOT NULL COMMENT '時間',
  PRIMARY KEY (`IMG_ID`),
  FOREIGN KEY (`MER_ID`) REFERENCES `MER` (`MER_ID`)
) COMMENT '商品的圖片';

CREATE TABLE `petting`.`BUS_ART` (
  `ART_ID` int NOT NULL AUTO_INCREMENT COMMENT '文章ID',
  `BUS_ID` int NOT NULL COMMENT '商家ID',
  `TITLE` varchar(25) NOT NULL COMMENT '標題',
  `ARTICLE` varchar(500) NOT NULL COMMENT '內文',
  `TIME` date NOT NULL COMMENT '時間',
  PRIMARY KEY (`ART_ID`),
  FOREIGN KEY (`BUS_ID`) REFERENCES `BUS` (`BUS_ID`)
) COMMENT '商家文章';

CREATE TABLE `petting`.`BUS_ART_IMG` (
  `IMG_ID` INT NOT NULL AUTO_INCREMENT COMMENT '文章圖流水編號',
  `ART_ID` INT NOT NULL COMMENT '文章ID',
  `ART_PIC` BLOB NOT NULL COMMENT '圖片',
  `TIME` DATE NOT NULL COMMENT '時間',
  PRIMARY KEY (`IMG_ID`),
  FOREIGN KEY (`ART_ID`) REFERENCES `BUS_ART` (`ART_ID`)
) COMMENT '文章的圖片';

CREATE TABLE `petting`.`SERVICE` (
    `SER_ID` INT NOT NULL COMMENT '服務ID', 
    `BUS_ID` INT NOT NULL COMMENT '商家ID',
    `NAME` VARCHAR(25) NOT NULL COMMENT '名稱',
    `PRICE` INT NOT NULL COMMENT '價格',
    `TIME` DATE NOT NULL COMMENT '上架日期',
    `STATUS` VARCHAR(25) NOT NULL COMMENT '上架狀態',
    `DESCRIPTION` VARCHAR(250) NOT NULL COMMENT '描述',
    `HOLIDAY` VARCHAR(7) NOT NULL COMMENT '公休日',
    `AVAILABLE` VARCHAR(24) NOT NULL COMMENT '營業時間',
    `STOCK` VARCHAR(24) NOT NULL COMMENT '可預約數量',
    PRIMARY KEY (`SER_ID`),
    CONSTRAINT `FK_SERVICE_BUSID` FOREIGN KEY (`BUS_ID`) REFERENCES `BUS` (`BUS_ID`)
) COMMENT '服務資料表';

CREATE TABLE `petting`.`SER_IMG` (
    `ID` INT AUTO_INCREMENT COMMENT '流水編號',
    `SER_ID` INT NOT NULL COMMENT '服務ID',
    `SER_IMG` BLOB COMMENT '圖片', 
    `TIME` DATE NOT NULL COMMENT '時間',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_SERIMG_SERID` FOREIGN KEY (`SER_ID`) REFERENCES `SERVICE` (`SER_ID`)
) COMMENT '服務的圖片';

CREATE TABLE `petting`.`PAYMENT` (
  `PAYMENT_ID` INT NOT NULL AUTO_INCREMENT COMMENT '付款方式編號',
  `PAYMENT_METHOD` VARCHAR(10) NOT NULL COMMENT '付款方式',
  PRIMARY KEY (`PAYMENT_ID`)
) COMMENT '付款方式資料表';

CREATE TABLE `petting`.`SHIPPING` (
    `SHIPPING_ID` INT NOT NULL COMMENT '出貨方式編號',
    `SHIPPING_METHOD` VARCHAR(10) NOT NULL COMMENT '出貨方式',
	PRIMARY KEY (`SHIPPING_ID`)
) COMMENT '出貨方式資料表';

CREATE TABLE `petting`.`ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT COMMENT '訂單流水編號',
  `MEMBER_ID` INT NOT NULL COMMENT '會員ID',
  `BUS_ID` INT NOT NULL COMMENT '商家ID',
  `ORDER_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '訂購時間',
  `ORDER_SUM` INT NOT NULL COMMENT '總金額',
  `PAYMENT_ID` INT NOT NULL COMMENT '付款方式編號',
  `SHIPPING_ID` INT NOT NULL COMMENT '出貨方式編號',
  `TRACKING` INT NULL COMMENT '追蹤碼',
  `ORDER_STATUS` INT NOT NULL DEFAULT 1 COMMENT '訂單狀態',
  `INVOICE_ID` VARCHAR(10) NULL COMMENT '發票號碼',
  `RECEIVER` VARCHAR(25) NOT NULL COMMENT '收件人',
  `RECEIVER_ADDR` VARCHAR(50) NOT NULL COMMENT '收件地址',
  `RECEIVER_PHONE` VARCHAR(25) NOT NULL COMMENT '收件電話',
  PRIMARY KEY (`ORDER_ID`),
  FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBERS`(`MEMBER_ID`),
  FOREIGN KEY (`BUS_ID`) REFERENCES `BUS`(`BUS_ID`),
  FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENT`(`PAYMENT_ID`), 
  FOREIGN KEY (`SHIPPING_ID`) REFERENCES `SHIPPING`(`SHIPPING_ID`)
) COMMENT = '商品訂單資料表';

CREATE TABLE `petting`.`ORDER_DETAIL` (
  `ORDER_ID` INT NOT NULL COMMENT '訂單流水編號',
  `MER_ID` INT NOT NULL COMMENT '商品ID',
  `QTY` INT NOT NULL COMMENT '商品數量',
  `UNIT_PRICE` INT NOT NULL COMMENT '商品單價',
  `RANKING` INT NULL COMMENT '評價',
  `COMMENT` VARCHAR(250) NULL COMMENT '評價文字',
  PRIMARY KEY (`ORDER_ID`, `MER_ID`),
  FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
  FOREIGN KEY (`MER_ID`) REFERENCES `MER`(`MER_ID`)
) COMMENT = '商品訂單明細';

CREATE TABLE `petting`.`SERORDER` (
    `ORDER_ID` INT NOT NULL COMMENT '訂單編號',
    `MEMBER_ID` INT NOT NULL COMMENT '會員ID',
    `BUS_ID` INT NOT NULL COMMENT '商家ID',
    `ORDER_TIME` TIMESTAMP NOT NULL COMMENT '訂購時間',
    `TOTAL` INT NOT NULL COMMENT '總金額',
    `ORD_STATUS` INT NOT NULL DEFAULT 1 COMMENT '訂單狀態',
    `INVOICE_ID` VARCHAR(10) COMMENT '發票號碼',
    `RECEIVER` VARCHAR(25) NOT NULL COMMENT '訂購人',
    `RECEIVER_PHONE` VARCHAR(25) NOT NULL COMMENT '訂購人電話',
    PRIMARY KEY (`ORDER_ID`),
    CONSTRAINT `FK_SERORDER_MEMBERID` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBERS` (`MEMBER_ID`),
    CONSTRAINT `FK_SERORDER_BUSID` FOREIGN KEY (`BUS_ID`) REFERENCES `BUS` (`BUS_ID`)
) COMMENT '服務訂單資料表';

CREATE TABLE `petting`.`SERORDER_DETAIL` (
    `ORDER_ID` INT NOT NULL COMMENT '訂單編號',
    `SER_ID` INT NOT NULL COMMENT '服務ID',
    `SER_DATE` DATE NOT NULL COMMENT '服務日期',
    `SER_QTY` VARCHAR(24) NOT NULL COMMENT '預約數量',
    `UNIT_PRICE` INT NOT NULL COMMENT '單價',
    COMMENT VARCHAR(250) COMMENT '評價文字',
    PRIMARY KEY (`ORDER_ID`, `SER_ID`),
    CONSTRAINT `FK_SERORDERDETAIL_ORDERID` FOREIGN KEY (`ORDER_ID`)
    REFERENCES `SERORDER` (`ORDER_ID`),
    CONSTRAINT `FK_SERORDERDETAIL_SERID` FOREIGN KEY (`SER_ID`)
    REFERENCES `SERVICE` (`SER_ID`)
) COMMENT '服務訂單明細';

  CREATE TABLE `petting`.`CS_DETAIL` (
  `CASE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '客服案流水號',
  `MEMBER_ID` INT NOT NULL COMMENT '會員ID',
  `BUS_ID` INT NOT NULL COMMENT '商家ID',
  `CASE_TIME` DATE NULL COMMENT '立案時間',
  `FEEDBACK` VARCHAR(500) NULL COMMENT '意見內容',
  `REPLY_STATUS` INT NOT NULL DEFAULT 1 COMMENT '回覆狀態',
  `REPLY_CONTENT` VARCHAR(500) NULL COMMENT '回覆內容',
  `REPLY_TIME` DATE NULL COMMENT '回覆時間',
  PRIMARY KEY (`CASE_ID`),
  FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBERS`(`MEMBER_ID`),
  FOREIGN KEY (`BUS_ID`) REFERENCES `BUS`(`BUS_ID`)
  ) COMMENT = '客服明細';